packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      StorageProvider:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: storageprovider.go
          pkgname: storagemocks
      StorageObjectProvider:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: storageobjectprovider.go
          pkgname: storagemocks
