name: Pull Request

permissions:
  contents: read
  id-token: write

on:
  pull_request:

jobs:
  integration-tests:
    uses: ./.github/workflows/integration_tests.yml
  publish-test-results:
    needs:
      - integration-tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          # Docker build artifacts have to ignored
          # https://github.com/actions/toolkit/pull/1874
          pattern: "!*.dockerbuild"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          fail_on: 'errors'
          files: "artifacts/**/*.xml"
